### ISSUE TITLE
tagSentence 메소드의 Synchronous 방식 메소드 추가의 건

### ISSUE THREAD

**Issue by chojunki** [nearbydelta/nodejs-koalanlp#5]
### 기초정보
- Node.js 버전은요? 8.11.1?
- KoalaNLP 버전은요? 최신버전(2018-06-19일자)?
- 문제의 유형은 어떤 것인가요? (Type of this issue)?
    - [ ] 기타. Other

### 재연을 위한 정보
N/A

### 본문
오픈소스 챗봇에 nodejs-koalanlp를 연계하려고 합니다. 챗봇 엔진 자체는 async로 되어 있는것으로 판단되지만 내부에서 자연어 처리를 하는 부분(물론 한국어는 존재하지 않고)은 synchronize 방식으로 구현되어 있어 Promise 객체를 리턴하여 async방식을 적용하자니 거의 재개발 비슷한 작업까지 될 것 같아 엄두를 못 내고 있는 상황입니다. 토크나이징과 태깅부분만 살짝 바꿔 사용하면 될것 같은데 구현방식이 아예 다르네요.

tagSentence 메소드를 sync방식으로 사용하면 될것 같은데 api.js를 보니 Java 클래스의 tagSentenceSync 메소드를 사용한 듯한 부분이 있네요. 이걸 node.js에서 직접 사용하려면 어떻게 해야 할까요?

10년간의 공백 뒤 다시 JavaScript를 다루려니 패러다임이 너무 많이 바뀌어 혼란스럽습니다. 콜백에 좌절한 지 얼마나 됐다고 이젠 Promise가 덤비고 있네요.

읽어주셔서 감사합니다.

**Comment by nearbydelta** [comment]
Synchronous 형태로 쓰시려면, Java의 Sentence 객체를 Javascript용으로 변환하는 코드를 사용하셔야 하는데, 이 부분이 Export가 안되어 있습니다. 그래서 Promise를 사용하여 결과값이 나올때까지 대기하여 sync로 부르시는 게 구현이 편하실 것이라고 생각합니다. `await` 키워드를 사용하면 node.js 7.6+에서 promise를 마치 sync로 사용하듯이 할 수 있는 것으로 알고 있습니다. 다음과 같이 하면 될 것 같습니다.

```javascript
let tagged = await tagger.tagSentence(sentence)
```

죄송하지만, 지금 작성중인 컴퓨터가 아직 node 6버전대라, 코드가 돌아가는지 테스트해보지는 못했습니다.

**Comment by nearbydelta** [comment]
테스트 해봤는데 되지 않네요. async/await 방식으로 변경해드리겠습니다.

**Comment by nearbydelta** [comment]
이제 1.3.4 버전에서 Sync method들을 사용하시면 됩니다.

```javascript
let tagged = tagger.tagSentenceSync(sentence)
```
